INSERT INTO USER(USERNAME, PASSWORD, ENABLED) VALUES('lyes', '$2a$04$FQb603owMsZ2xCTtFSslsOvQ9bUSUatuemwR9IX1ebF7iKsOASF66', TRUE);
INSERT INTO USERROLE(ID, ROLE, USER_ID) VALUES(1, 'ROLE_ADMIN', 'lyes');

INSERT INTO USER(USERNAME, PASSWORD, ENABLED) VALUES('kher', '$2a$04$S8gZ6H0A1UJAKuihtrXEd.FOPpvYyQQCNJAhm1MmKrUQumGHPRRLq', TRUE);
INSERT INTO USERROLE(ID, ROLE, USER_ID) VALUES(2, 'ROLE_COUNSELOR', 'kher');
